spring:
  application:
    name:myRest
  datasource:
    url: jdbc:postgresql://localhost:5432/my_rest_db
    username: postgres
    password: aymen
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
